In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [31]:
import pandas as pd
df=pd.read_csv('/content/gdrive/My Drive/Titanic-Dataset.csv')

In [ ]:
# Creating a Dataframe having only fare column
fare = df[['Fare']]

# Print the head of the result
fare.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

In [ ]:
# Create a DataFrame containing only the Pclass and Age columns
class_age = df[['Pclass', 'Age']]

# Print the head of the result
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [ ]:

# Create a DataFrame containing only the Survived and Sex columns
survived_gender = df[['Survived', 'Sex']]

# Print the head of the result
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

In [ ]:
# Filter the dataset for fares greater than 100
fare_gt_100 = df[df['Fare'] > 100]

# Print the result
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [ ]:
# Filter the dataset for females under 18
female_under_18 = df[(df['Age'] < 18) & (df['Sex'] == 'female')]

# Print the result
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

In [ ]:
# Filter the dataset for passengers who embarked at Cherbourg or Southampton
embarked_c_or_s = df[df['Embarked'].isin(['C', 'S'])]

# Print the result
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Filter the dataset for passengers in first or second class
first_second_class = df[df['Pclass'].isin([1, 2])]

# Print the result
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [ ]:
# Add a new column 'fare_per_year' to the DataFrame
# To avoid division by zero, we can replace 'Age' values of 0 with NaN
df['fare_per_year'] = df['Fare'] / df['Age'].replace(0, pd.NA)

# Print the updated DataFrame to see the new column
df[['Fare', 'Age', 'fare_per_year']].head()

      Fare   Age  fare_per_year
0   7.2500  22.0       0.329545
1  71.2833  38.0       1.875876
2   7.9250  26.0       0.304808
3  53.1000  35.0       1.517143
4   8.0500  35.0       0.230000

In [ ]:
# Add a new column 'fare_per_year' to the DataFrame
df['fare_per_year'] = df['Fare'] / df['Age'].replace(0, pd.NA)

# Subset rows where fare_per_year is greater than 5
high_fare_age = df[df['fare_per_year'] > 5]

# Print the result
high_fare_age.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,5.669643

In [ ]:


# Sort high_fare_age by descending fare_per_year
high_fare_age_srt = high_fare_age.sort_values(by='fare_per_year', ascending=False)

# Print the sorted result
high_fare_age_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,39.000000

In [ ]:
# Filter the dataset for passengers in first class
first_class = df[df['Pclass'] == 1]

# Print the result
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [ ]:
# Select only the Name and fare_per_year columns
result = high_fare_age_srt[['Name', 'fare_per_year']]

# Look at the result
result.head()

                                Name  fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

In [ ]:
# Calculate the total Fare paid across all passengers
total_fare = df['Fare'].sum()

# Print the total fare
total_fare

28693.9493

In [ ]:
# Subset for passengers in first class (Pclass is 1)
first_class_passengers = df[df['Pclass'] == 1]

# Calculate the total fare for first class passengers
total_fare_first_class = first_class_passengers['Fare'].sum()

# Print the total fare
total_fare_first_class

18177.4125

In [ ]:
# Calculate total fare for second class passengers (Pclass is 2)
second_class_passengers = df[df['Pclass'] == 2]
total_fare_second_class = second_class_passengers['Fare'].sum()
total_fare_second_class

# Calculate total fare for third class passengers (Pclass is 3)
third_class_passengers = df[df['Pclass'] == 3]
total_fare_third_class = third_class_passengers['Fare'].sum()
total_fare_third_class

6714.6951

In [ ]:
# Combine the fare totals into a list
fare_totals = [total_fare_first_class, total_fare_second_class, total_fare_third_class]

# Print the list of fare totals
fare_totals

[18177.4125, 3801.8417, 6714.6951]

In [32]:
# Calculate the proportion of fare revenue by class
fare_proportion_by_class = [total_fare_first_class / total_fare, total_fare_second_class / total_fare, total_fare_third_class / total_fare]

fare_proportion_by_class

[0.6334928771899656, 0.1324962855496507, 0.23401083726038366]

In [34]:
# Create the 'Age Group' column using .loc
df['Age Group'] = 'unknown'  # Default value in case of missing or undefined ages

# Assign 'child' to ages less than 18
df.loc[df['Age'] < 18, 'Age Group'] = 'child'

# Assign 'adult' to ages between 18 and 64
df.loc[(df['Age'] >= 18) & (df['Age'] < 65), 'Age Group'] = 'adult'

# Assign 'senior' to ages 65 and above
df.loc[df['Age'] >= 65, 'Age Group'] = 'senior'

# Check the result
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,adult

In [35]:
#Calculate the total number of passengers
total_passengers = df.shape[0]

total_passengers

891

In [36]:
# Count the number of passengers in each age group
age_group_counts = df['Age Group'].value_counts()

age_group_counts

Age Group
adult      590
unknown    177
child      113
senior      11
Name: count, dtype: int64

In [37]:
#Calculate the proportion of passengers in each age group
age_group_proportions = age_group_counts / total_passengers

age_group_proportions

Age Group
adult      0.662177
unknown    0.198653
child      0.126824
senior     0.012346
Name: count, dtype: float64

In [38]:
#Convert proportions to percentages
age_group_percentages = age_group_proportions * 100

age_group_percentages

Age Group
adult      66.217733
unknown    19.865320
child      12.682379
senior      1.234568
Name: count, dtype: float64